inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('inventory_app.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from . import views

from .views import home
from .views import warehouse
from .views import item_category
from .views import item
from .views import stock
from .views import photo

app_name = "inventory_app"

urlpatterns = [
    path('', home.index, name="index"),

    # page URLs
    path('dashboard/', home.view_dashboard, name="view_dashboard"),
    path('calendar/', home.view_calender, name="view_calendar"),

    # Warehouse URLs
    path('view-warehouse-table/', warehouse.view_warehouse_table,
         name="view_warehouse_table"),
    path('add-warehouse/', warehouse.add_warehouse,
         name="add_warehouse"),
    path('update-warehouse/<id>/', warehouse.update_warehouse,
         name="update_warehouse"),
    path('delete-warehouse/<id>/', warehouse.delete_warehouse,
         name="delete_warehouse"),
    
     # item-category URLs
    path('view-item-category-table/', item_category.view_item_category_table,
         name="view_item_category_table"),
    path('add-item-category/', item_category.add_item_category,
         name="add_item_category"),
    path('update-item-category/<id>/', item_category.update_item_category,
         name="update_item_category"),
    path('delete-item-category/<id>/', item_category.delete_item_category,
         name="delete_item_category"),

    # Stock URLs
    path('view-stock-table/', stock.view_stock_table, name="view_stock_table"),
    path('add-stock/', stock.add_stock,
         name="add_stock"),
    path('update-stock/<id>/', stock.update_stock,
         name="update_stock"),
    path('delete-stock/<id>/', stock.delete_stock,
         name="delete_stock"),

    # Item URLs
    path('view-item-table/', item.view_item_table, name="view_item_table"),
    path('add-item/', item.add_item,
         name="add_item"),
    path('get-units/', item.get_units, name='get_units'),
    path('update-item/<id>/', item.update_item,
         name="update_item"),
    path('delete-item/<id>/', item.delete_item,
         name="delete_item"),

    # Photo URLs
    path('view-photo-table/', photo.view_photo_table, name="view_photo_table"),
    path('add-photo/', photo.add_photo,
         name="add_photo"),
    path('get_item_photos/', photo.get_item_photos, name='get_item_photos'),
    path('update-photo/<id>/', photo.update_photo,
         name="update_photo"),
    path('delete-photo/<id>/', photo.delete_photo,
         name="delete_photo"),
]

inventory_app/views/stock.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator

from ..models import Warehouse, Stock, Item
from ..forms import StockForm


# ======================== Stock Views ==========================#

def view_stock_table(request):

    stocks = Stock.objects.all()
    table_name = "Stock"
    context = {
        'table_name': table_name,
        'stocks': stocks
    }
    return render(request, "contents/all-table/stocks.html", context)


def add_stock(request):

    context = {}
    data = {}

    items = Item.objects.all()
    warehouses = Warehouse.objects.all()

    context['items'] = items
    context['warehouses'] = warehouses

    context['table_name'] = "stock"
    context['stocks'] = Stock.objects.all()

    data['valid'] = False
    data['add_stock_form'] = render_to_string(
        'contents/stock/add-stock-form.html', context, request=request)

    if request.method == "POST":
        form = StockForm(request.POST)

        if form.is_valid():
            form.save()

            context['alert_message'] = 'Successfully Added a stock'
            # update context after save
            context['stocks'] = Stock.objects.all()
            context['items'] = items
            context['warehouses'] = warehouses

            data['valid'] = True
            data['stock_list'] = render_to_string(
                'contents/stock/stock-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)

    return JsonResponse(data)


def update_stock(request, id):

    context = {}
    data = {}

    single_stock = get_object_or_404(Stock, id=id)
    warehouses = Warehouse.objects.all()
    items = Item.objects.all()

    context['single_stock'] = single_stock
    context['items'] = items
    context['warehouses'] = warehouses

    context['stocks'] = Stock.objects.all()

    data['valid'] = False
    data['update_stock_form'] = render_to_string(
        'contents/stock/update-stock-form.html', context, request=request)

    if request.method == 'POST':
        form = StockForm(request.POST, request.FILES,
                         instance=single_stock)

        if form.is_valid():
            form.save()

            context['stocks'] = Stock.objects.all()
            context['alert_message'] = 'Successfully Updated a stock'

            data['valid'] = True
            data['stock_list'] = render_to_string(
                'contents/stock/stock-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)

    return JsonResponse(data)


def delete_stock(request, id):

    context = {}
    data = {}

    single_stock = get_object_or_404(Stock, id=id)

    context['single_stock'] = single_stock
    context['stocks'] = Stock.objects.all()

    data['valid'] = False
    data['delete_stock_form'] = render_to_string(
        'contents/stock/delete-stock-form.html', context, request=request)

    if request.method == 'POST':
        single_stock.delete()

        context['stocks'] = Stock.objects.all()
        context['alert_message'] = 'Successfully Deleted a stock'

        data['valid'] = True
        data['stock_list'] = render_to_string(
            'contents/stock/stock-list.html', context, request=request)
        data['alert_box'] = render_to_string(
            'includes/alert-box.html', context, request=request)

    return JsonResponse(data)

templates/contents/stock/add-stock-form.html
<form action="{% url 'inventory_app:add_stock' %}" method="post" class="add_stock_form">
  {% csrf_token %}

  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Stock Form</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label class="form-label" for="item">Item</label>
      <select class="form-control" name="item" id="warehouse" required>
        <option value="" disabled selected>Select Item</option>
        {% for item in items %}
          <option value="{{ item.id }}">{{ item.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label class="form-label" for="warehouse">Warehouse</label>
      <select class="form-control" name="warehouse" id="warehouse" required>
        <option value="" disabled selected>Select Warehouse</option>
        {% for warehouse in warehouses %}
          <option value="{{ warehouse.id }}">{{ warehouse.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label class="form-label" for="quantity">Quantity</label>
      <input class="form-control" name="quantity" id="quantity" type="number" step="1" placeholder="Quantity" required />
    </div>

    <div class="mb-3">
      <label class="form-label" for="last_quantity_added">Last Quantity Added</label>
      <input class="form-control" name="last_quantity_added" id="last_quantity_added" type="number" step="1" placeholder="Last Quantity Added" required />
    </div>

    <div class="mb-3">
      <label class="form-label" for="last_quantity_reduced">Last Quantity Reduced</label>
      <input class="form-control" name="last_quantity_reduced" id="last_quantity_reduced" type="number" step="1" placeholder="Last Quantity Reduced" required />
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

templates/contents/stock/delete-stock-form.html
<form action="{% url 'inventory_app:delete_stock' single_stock.id %}" method="post" class="delete_stock_form">
  {% csrf_token %}

  <div class="modal-header">
    <h4 class="modal-title" id="exampleModalLabel">Confirmation of Delete Stock</h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <h6>
      Are you sure you want to delete the stock of <strong>{{ single_stock.item }}</strong>
      from <strong>{{ single_stock.warehouse }}</strong> ?
    </h6>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

templates/contents/stock/stock-list.html
{% for stock in stocks %}
  <tr>
    <td class="align-middle ps-3 name">
      <input type="checkbox" name="" id="" />
    </td>
    <td class="align-middle ps-3">{{ forloop.counter }}</td>
    <td class="align-middle ps-3">{{ stock.item }}</td>
    <td class="align-middle">{{ stock.warehouse }}</td>
    <td class="align-middle">{{ stock.quantity }}</td>
    <td class="align-middle">{{ stock.last_quantity_added }}</td>
    <td class="align-middle">{{ stock.last_quantity_reduced }}</td>

    <td class="align-middle white-space-nowrap text-end pe-0">
      <div class="btn-reveal-trigger position-static">
        <button class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs-10" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent"><span class="fas fa-ellipsis-h fs-10"></span></button>

        <div class="dropdown-menu dropdown-menu-end py-2">
          <a class="dropdown-item" href="#!">View</a>
          <a class="dropdown-item update_stock_button" href="{% url 'inventory_app:update_stock' stock.id %}">Edit</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger delete_stock_button" href="{% url 'inventory_app:delete_stock' stock.id %}">Remove</a>
        </div>
      </div>
    </td>
  </tr>
{% endfor %}

templates/contents/stock/update-stock-form.html
<form action="{% url 'inventory_app:update_stock' single_stock.id %}" method="post" class="update_stock_form">
    {% csrf_token %}
    <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Update Stock Form</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">

        <div class="mb-3">
            <label class="form-label" for="item">Item</label>
            <select class="form-control" name="item" id="item" required>
                <option value="" disabled>Select Item</option>
                {% for item in items %}
                    <option value="{{ item.id }}" {% if item.id == single_stock.item.id %}selected{% endif %}>
                        {{ item.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label class="form-label" for="warehouse">Warehouse</label>
            <select class="form-control" name="warehouse" id="warehouse" required>
                <option value="" disabled>Select Warehouse</option>
                {% for warehouse in warehouses %}
                <option value="{{ warehouse.id }}" {% if warehouse.id == single_stock.warehouse.id %}selected{% endif %}>
                    {{warehouse.name }}
                </option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label class="form-label" for="quantity">Quantity</label>
            <input class="form-control" name="quantity" value="{{ single_stock.quantity }}" id="quantity" type="number"
                step="1" placeholder="Quantity" required />
        </div>

        <div class="mb-3">
            <label class="form-label" for="last_quantity_added">Last Quantity Added</label>
            <input class="form-control" name="last_quantity_added" value="{{ single_stock.last_quantity_added }}"
                id="last_quantity_added" type="number" step="1" placeholder="Last Quantity Added" required />
        </div>

        <div class="mb-3">
            <label class="form-label" for="last_quantity_reduced">Last Quantity Reduced</label>
            <input class="form-control" name="last_quantity_reduced" value="{{ single_stock.last_quantity_reduced }}"
                id="last_quantity_reduced" type="number" step="1" placeholder="Last Quantity Reduced" required />
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>