inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('inventory_app.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from . import views

from .views import home
from .views import warehouse
from .views import item_category
from .views import item
from .views import stock
from .views import photo

app_name = "inventory_app"

urlpatterns = [
    path('', home.index, name="index"),

    # page URLs
    path('dashboard/', home.view_dashboard, name="view_dashboard"),
    path('calendar/', home.view_calender, name="view_calendar"),

    # Warehouse URLs
    path('view-warehouse-table/', warehouse.view_warehouse_table,
         name="view_warehouse_table"),
    path('add-warehouse/', warehouse.add_warehouse,
         name="add_warehouse"),
    path('update-warehouse/<id>/', warehouse.update_warehouse,
         name="update_warehouse"),
    path('delete-warehouse/<id>/', warehouse.delete_warehouse,
         name="delete_warehouse"),
    
     # item-category URLs
    path('view-item-category-table/', item_category.view_item_category_table,
         name="view_item_category_table"),
    path('add-item-category/', item_category.add_item_category,
         name="add_item_category"),
    path('update-item-category/<id>/', item_category.update_item_category,
         name="update_item_category"),
    path('delete-item-category/<id>/', item_category.delete_item_category,
         name="delete_item_category"),

    # Stock URLs
    path('view-stock-table/', stock.view_stock_table, name="view_stock_table"),
    path('add-stock/', stock.add_stock,
         name="add_stock"),
    path('update-stock/<id>/', stock.update_stock,
         name="update_stock"),
    path('delete-stock/<id>/', stock.delete_stock,
         name="delete_stock"),

    # Item URLs
    path('view-item-table/', item.view_item_table, name="view_item_table"),
    path('add-item/', item.add_item,
         name="add_item"),
    path('get-units/', item.get_units, name='get_units'),
    path('update-item/<id>/', item.update_item,
         name="update_item"),
    path('delete-item/<id>/', item.delete_item,
         name="delete_item"),

    # Photo URLs
    path('view-photo-table/', photo.view_photo_table, name="view_photo_table"),
    path('add-photo/', photo.add_photo,
         name="add_photo"),
    path('get_item_photos/', photo.get_item_photos, name='get_item_photos'),
    path('update-photo/<id>/', photo.update_photo,
         name="update_photo"),
    path('delete-photo/<id>/', photo.delete_photo,
         name="delete_photo"),
]

inventory_app/views/photo.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator

from ..models import Item, Photo
from ..forms import PhotoForm


# ======================== Photo Views ==========================#

def view_photo_table(request):

    photos = Photo.objects.all()
    table_name = "Photo"
    context = {
        'table_name': table_name,
        'photos': photos
    }
    return render(request, "contents/all-table/photos.html", context)


def get_item_photos(request):
    item_id = request.GET.get('item_id')
    photos = Photo.objects.filter(item_id=item_id)
    photo_data = [{'url': photo.photo.url} for photo in photos]
    return JsonResponse({'photos': photo_data})


def add_photo(request):
    context = {}
    data = {}

    items = Item.objects.all()
    context['items'] = items
    context['table_name'] = "Photo"
    context['photos'] = Photo.objects.all()

    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            context['alert_message'] = 'Successfully Added a Photo'
            data['valid'] = True
            data['photo_list'] = render_to_string(
                'contents/photo/photo-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)
        else:
            data['valid'] = False
            data['errors'] = form.errors

    data['add_photo_form'] = render_to_string(
        'contents/photo/add-photo-form.html', context, request=request)

    return JsonResponse(data)


def update_photo(request, id):

    context = {}
    data = {}

    items = Item.objects.all()
    single_photo = get_object_or_404(Photo, id=id)

    context['items'] = items
    context['table_name'] = "Photo"
    context['photos'] = Photo.objects.all()
    context['single_photo'] = single_photo

    data['valid'] = False
    data['update_photo_form'] = render_to_string(
        'contents/photo/update-photo-form.html', context, request=request)

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES,
                         instance=single_photo)

        if form.is_valid():
            form.save()

            context['photos'] = Photo.objects.all()
            context['single_photo'] = single_photo
            context['alert_message'] = 'Successfully Updated a Photo'

            data['valid'] = True
            data['photo_list'] = render_to_string(
                'contents/photo/photo-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)

    return JsonResponse(data)


def delete_photo(request, id):

    context = {}
    data = {}

    single_photo = get_object_or_404(Photo, id=id)

    context['single_photo'] = single_photo
    context['photos'] = Photo.objects.all()

    data['valid'] = False
    data['delete_photo_form'] = render_to_string(
        'contents/photo/delete-photo-form.html', context, request=request)

    if request.method == 'POST':
        single_photo.delete()

        context['photos'] = Photo.objects.all()
        context['alert_message'] = 'Successfully Deleted a photo'

        data['valid'] = True
        data['photo_list'] = render_to_string(
            'contents/photo/photo-list.html', context, request=request)
        data['alert_box'] = render_to_string(
            'includes/alert-box.html', context, request=request)

    return JsonResponse(data)

templates/contents/photo/add-photo-form.html
<form action="{% url 'inventory_app:add_photo' %}" method="post" class="add_photo_form" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Photo Form</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <div class="mb-3">
      <label class="form-label" for="item">Item</label>
      <select class="form-control" name="item" id="item-select" required>
        <option value="" disabled selected>Select Item</option>
        {% for item in items %}
          <option value="{{ item.id }}">{{ item.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label class="form-label" for="photo">Upload Photos</label>
      <!-- Existing Image Preview Area -->
      <div id="existing-photo-preview-container"></div>
      <!-- Uploaded Image Preview Area -->
      <div id="photo-preview-container">
        <div id="photo-previews"></div>
      </div>
      <input class="form-control" name="photo" id="photos" type="file" accept="image/*" multiple />
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

<script>
  document.getElementById('photos').addEventListener('change', function (event) {
    const files = event.target.files
    const previewContainer = document.getElementById('photo-preview-container')
  
    const previewDiv = document.getElementById('photo-previews')
    previewDiv.innerHTML = '' // Clear previous previews
  
    const div = document.createElement('div')
    div.innerHTML = '<small>Newly Uploaded Image</small>'
    previewDiv.appendChild(div)
  
    if (files.length > 0) {
      Array.from(files).forEach((file) => {
        const reader = new FileReader()
        reader.onload = function (e) {
          const img = document.createElement('img')
          img.src = e.target.result
          img.style.maxWidth = '25%'
          img.style.height = 'auto'
          img.style.marginBottom = '10px'
          img.style.marginRight = '5px'
          previewDiv.appendChild(img)
        }
        reader.readAsDataURL(file)
      })
      previewContainer.style.display = 'block'
    } else {
      previewContainer.style.display = 'none'
    }
  })
  
  document.getElementById('item-select').addEventListener('change', function () {
    const itemId = this.value
    fetch(`/get_item_photos/?item_id=${itemId}`)
      .then((response) => response.json())
      .then((data) => {
        const existingPhotoContainer = document.getElementById('existing-photo-preview-container')
        existingPhotoContainer.innerHTML = '' // Clear previous images
  
        const div = document.createElement('div')
        div.innerHTML = '<small>Previously Uploaded Images</small>'
        existingPhotoContainer.appendChild(div)
  
        data.photos.forEach((photo) => {
          const img = document.createElement('img')
          img.src = photo.url
          img.style.maxWidth = '25%'
          img.style.height = 'auto'
          img.style.marginBottom = '10px'
          img.style.marginRight = '5px'
          existingPhotoContainer.appendChild(img)
        })
      })
  })
</script>

templates/contents/photo/delete-photo-form.html
<form action="{% url 'inventory_app:delete_photo' single_photo.id %}" method="post" class="delete_photo_form">
  {% csrf_token %}

  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Confirmation of Delete Photo</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <h6>Are you sure you want to delete the photo of "{{ single_photo.item }}"?</h6>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

templates/contents/photo/photo-list.html
{% for photo in photos %}
  <tr>
    <td class="align-middle ps-3 name">
      <input type="checkbox" name="" id="" />
    </td>
    <td class="align-middle ps-3">{{ forloop.counter }}</td>
    <td class="align-middle ps-3">{{ photo.item }}</td>

    {% if photo.photo %}
      <td>
        <img class="align-middle" width="30" height="30" src="{{ photo.photo.url }}" alt="item image" />
      </td>
    {% else %}
      <td class="align-middle">N/A</td>
    {% endif %}

    <td class="align-middle white-space-nowrap text-end pe-0">
      <div class="btn-reveal-trigger position-static">
        <button class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs-10" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent"><span class="fas fa-ellipsis-h fs-10"></span></button>

        <div class="dropdown-menu dropdown-menu-end py-2">
          <a class="dropdown-item" href="#!">View</a>
          <a class="dropdown-item update_photo_button" href="{% url 'inventory_app:update_photo' photo.id %}">Edit</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger delete_photo_button" href="{% url 'inventory_app:delete_photo' photo.id %}">Remove</a>
        </div>
      </div>
    </td>
  </tr>
{% endfor %}

templates/contents/photo/update-photo-form.html
<form action="{% url 'inventory_app:update_photo' single_photo.id %}" method="post" class="update_photo_form" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Photo Form</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

    <div class="mb-3">
        <label class="form-label" for="item">Item</label>
        <select class="form-control" name="item" id="item" required>
            <option value="" disabled>Select Item</option>
            {% for item in items %}
                <option value="{{ item.id }}" {% if item.id == single_stock.item.id %}selected{% endif %}>
                    {{ item.name }}
                </option>
            {% endfor %}
        </select>
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Upload Photo</label>
        {% if single_photo.photo %}
          <div>
            <img src="{{ single_photo.photo.url }}" alt="Current photo" style="max-width: 25%; height: auto;" />
            <small>{{ single_photo.photo.url }}</small>
          </div>
        {% endif %}
        <input type="file" name="photo" class="form-control" id="exampleFormControlInput1" />
      </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>