inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('inventory_app.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from . import views

from .views import home
from .views import warehouse
from .views import item_category
from .views import item
from .views import stock
from .views import photo

app_name = "inventory_app"

urlpatterns = [
    path('', home.index, name="index"),

    # page URLs
    path('dashboard/', home.view_dashboard, name="view_dashboard"),
    path('calendar/', home.view_calender, name="view_calendar"),

    # Warehouse URLs
    path('view-warehouse-table/', warehouse.view_warehouse_table,
         name="view_warehouse_table"),
    path('add-warehouse/', warehouse.add_warehouse,
         name="add_warehouse"),
    path('update-warehouse/<id>/', warehouse.update_warehouse,
         name="update_warehouse"),
    path('delete-warehouse/<id>/', warehouse.delete_warehouse,
         name="delete_warehouse"),
    
     # item-category URLs
    path('view-item-category-table/', item_category.view_item_category_table,
         name="view_item_category_table"),
    path('add-item-category/', item_category.add_item_category,
         name="add_item_category"),
    path('update-item-category/<id>/', item_category.update_item_category,
         name="update_item_category"),
    path('delete-item-category/<id>/', item_category.delete_item_category,
         name="delete_item_category"),

    # Stock URLs
    path('view-stock-table/', stock.view_stock_table, name="view_stock_table"),
    path('add-stock/', stock.add_stock,
         name="add_stock"),
    path('update-stock/<id>/', stock.update_stock,
         name="update_stock"),
    path('delete-stock/<id>/', stock.delete_stock,
         name="delete_stock"),

    # Item URLs
    path('view-item-table/', item.view_item_table, name="view_item_table"),
    path('add-item/', item.add_item,
         name="add_item"),
    path('get-units/', item.get_units, name='get_units'),
    path('update-item/<id>/', item.update_item,
         name="update_item"),
    path('delete-item/<id>/', item.delete_item,
         name="delete_item"),

    # Photo URLs
    path('view-photo-table/', photo.view_photo_table, name="view_photo_table"),
    path('add-photo/', photo.add_photo,
         name="add_photo"),
    path('get_item_photos/', photo.get_item_photos, name='get_item_photos'),
    path('update-photo/<id>/', photo.update_photo,
         name="update_photo"),
    path('delete-photo/<id>/', photo.delete_photo,
         name="delete_photo"),
]

inventory_app/views/item_category.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator

from ..models import ItemCategory
from ..forms import ItemCategoryForm


# ======================== Item Category Views ==========================#

def view_item_category_table(request):
    item_categories = ItemCategory.objects.all()
    table_name = "Item Category"

    context = {
        'title': 'Inventory',
        'table_name': table_name,
        'item_categories': item_categories,
    }
    return render(request, "contents/all-table/item-categories.html", context)


def add_item_category(request):
    context = {}
    data = {}

    item_categories = ItemCategory.objects.all()

    context['item_categories'] = item_categories

    data['valid'] = False
    data['add_item_category_form'] = render_to_string(
        'contents/item-category/add-item-category-form.html', context, request=request)

    if request.method == "POST":
        form = ItemCategoryForm(request.POST)

        if form.is_valid():
            form.save()
            context['alert_message'] = 'Successfully Added a Item Category'
            # update context after save
            context['item_categories'] = ItemCategory.objects.all()
            data['valid'] = True
            data['item_category_list'] = render_to_string(
                'contents/item-category/item-category-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)
        else:
            print(form.errors)

    return JsonResponse(data)


def update_item_category(request, id):
    data = dict()
    context = {}

    single_item_category = ItemCategory.objects.get(id=id)

    if request.method == 'POST':
        form = ItemCategoryForm(request.POST, request.FILES,
                             instance=single_item_category)

        if form.is_valid():
            form.save()
            item_categories = ItemCategory.objects.all()
            context = {
                'item_categories': item_categories,
                'alert_message': 'Successfully Updated a Item Category'
            }
            data['valid'] = True
            data['item_category_list'] = render_to_string(
                'contents/item-category/item-category-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)
        else:
            data['update_item_category_form'] = render_to_string(
                'contents/item-category/update-item-category-form.html', {'single_item_category': single_item_category}, request=request)
            data['valid'] = False

    else:
        data['update_item_category_form'] = render_to_string(
            'contents/item-category/update-item-category-form.html', {'single_item_category': single_item_category}, request=request)

    return JsonResponse(data)


def delete_item_category(request, id):
    data = dict()

    single_item_category = ItemCategory.objects.get(id=id)

    if request.method == 'POST':
        single_item_category.delete()

        item_categories = ItemCategory.objects.all()
        context = {
            'item_categories': item_categories,
            'alert_message': 'Successfully Deleted a Item Category'
        }
        data['valid'] = True
        data['item_category_list'] = render_to_string(
            'contents/item-category/item-category-list.html', context, request=request)
        data['alert_box'] = render_to_string(
            'includes/alert-box.html', context, request=request)

    else:
        data['delete_item_category_form'] = render_to_string(
            'contents/item-category/delete-item-category-form.html', {'single_item_category': single_item_category}, request=request)
        
    return JsonResponse(data)

templates/contents/item-category/add-item-category-form.html
<form action="{% url 'inventory_app:add_item_category' %}" method="post" class="add_item_category_form">
  {% csrf_token %}
  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Item Category Form</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label class="form-label" for="exampleFormControlInput">Item Category Name</label>
      <input class="form-control" name="name" id="exampleFormControlInput" type="text" placeholder="Item Category Name" />
    </div>

    <div class="mb-3">
      <label class="form-label" for="exampleFormControlInput">Item Category Description</label>
      <input class="form-control" name="description" id="exampleFormControlInput" type="text" placeholder="Item Category Type" />
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

templates/contents/item-category/delete-item-category-form.html
<form action="{% url 'inventory_app:delete_item_category' single_item_category.id %}" method="post" class="delete_item_category_form">
  {% csrf_token %}

  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Confirmation of Delete Item Category</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <h6>Are you sure you want to delete the "{{ single_item_category.name }}"?</h6>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

templates/contents/item-category/item-category-list.html
{% for item_category in item_categories %}
  <tr>
    <td class="align-middle ps-3 name">
      <input type="checkbox" name="" id="" />
    </td>
    <td class="align-middle ps-3 name">{{ forloop.counter }}</td>
    <td class="align-middle ps-3 name">{{ item_category.name }}</td>
    <td class="align-middle ps-3 name">{{ item_category.description }}</td>
    <td class="align-middle white-space-nowrap text-end pe-0">
      <div class="btn-reveal-trigger position-static">
        <button class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs-10" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent"><span class="fas fa-ellipsis-h fs-10"></span></button>

        <div class="dropdown-menu dropdown-menu-end py-2">
          <a class="dropdown-item" href="#!">View</a>
          <a class="dropdown-item update_item_category_button" href="{% url 'inventory_app:update_item_category' item_category.id %}">Edit</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger delete_item_category_button" href="{% url 'inventory_app:delete_item_category' item_category.id %}">Remove</a>
        </div>
      </div>
    </td>
  </tr>
{% endfor %}

templates/contents/item-category/update-item-category-form.html
<form action="{% url 'inventory_app:update_item_category' single_item_category.id %}" method="post" class="update_item_category_form">
  {% csrf_token %}
  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Update Item Category</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label class="form-label" for="exampleFormControlInput">Item Category Name</label>
      <input class="form-control" name="name" value="{{ single_item_category.name }}" id="exampleFormControlInput" type="text" placeholder="Item Category Name" />
    </div>

    <div class="mb-3">
      <label class="form-label" for="exampleFormControlInput">Item Category Description</label>
      <input class="form-control" name="description" value="{{ single_item_category.description }}" id="exampleFormControlInput" type="text" placeholder="Item Category Type" />
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>