inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('inventory_app.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from . import views

from .views import home
from .views import warehouse
from .views import item_category
from .views import item
from .views import stock
from .views import photo

app_name = "inventory_app"

urlpatterns = [
    path('', home.index, name="index"),

    # page URLs
    path('dashboard/', home.view_dashboard, name="view_dashboard"),
    path('calendar/', home.view_calender, name="view_calendar"),

    # Warehouse URLs
    path('view-warehouse-table/', warehouse.view_warehouse_table,
         name="view_warehouse_table"),
    path('add-warehouse/', warehouse.add_warehouse,
         name="add_warehouse"),
    path('update-warehouse/<id>/', warehouse.update_warehouse,
         name="update_warehouse"),
    path('delete-warehouse/<id>/', warehouse.delete_warehouse,
         name="delete_warehouse"),
    
     # item-category URLs
    path('view-item-category-table/', item_category.view_item_category_table,
         name="view_item_category_table"),
    path('add-item-category/', item_category.add_item_category,
         name="add_item_category"),
    path('update-item-category/<id>/', item_category.update_item_category,
         name="update_item_category"),
    path('delete-item-category/<id>/', item_category.delete_item_category,
         name="delete_item_category"),

    # Stock URLs
    path('view-stock-table/', stock.view_stock_table, name="view_stock_table"),
    path('add-stock/', stock.add_stock,
         name="add_stock"),
    path('update-stock/<id>/', stock.update_stock,
         name="update_stock"),
    path('delete-stock/<id>/', stock.delete_stock,
         name="delete_stock"),

    # Item URLs
    path('view-item-table/', item.view_item_table, name="view_item_table"),
    path('add-item/', item.add_item,
         name="add_item"),
    path('get-units/', item.get_units, name='get_units'),
    path('update-item/<id>/', item.update_item,
         name="update_item"),
    path('delete-item/<id>/', item.delete_item,
         name="delete_item"),

    # Photo URLs
    path('view-photo-table/', photo.view_photo_table, name="view_photo_table"),
    path('add-photo/', photo.add_photo,
         name="add_photo"),
    path('get_item_photos/', photo.get_item_photos, name='get_item_photos'),
    path('update-photo/<id>/', photo.update_photo,
         name="update_photo"),
    path('delete-photo/<id>/', photo.delete_photo,
         name="delete_photo"),
]

inventory_app/views/item.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator

from ..models import Warehouse, Stock, ItemCategory, ItemUnit, Item, Photo, generate_unique_id
from ..forms import ItemForm


# ======================== Item Views ==========================#


def view_item_table(request):

    items = Item.objects.all()
    table_name = "Item"
    context = {
        'table_name': table_name,
        'items': items
    }
    return render(request, "contents/all-table/items.html", context)


def get_item_images(id):
    single_item = get_object_or_404(Item, id=id)

    # This will give you a QuerySet of all Photo instances related to this item
    single_item_photos = single_item.photos.all()

    return single_item_photos


def get_units(request):
    category_id = request.GET.get('category_id')
    units = ItemUnit.objects.filter(
        category_id=category_id).values('id', 'name')
    return JsonResponse(list(units), safe=False)


def add_item(request):
    context = {}
    data = {}

    warehouses = Warehouse.objects.all()
    categories = ItemCategory.objects.all()
    units = ItemUnit.objects.all()
    random_unique_id = generate_unique_id()

    context['warehouses'] = warehouses
    context['categories'] = categories
    context['units'] = units
    context['random_unique_id'] = random_unique_id
    context['table_name'] = "item"
    context['items'] = Item.objects.all()

    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)

            generate_barcode = 'barcode' in request.POST
            generate_qrcode = 'qrcode' in request.POST
            isbn = request.POST.get('isbn')
            serial_no = request.POST.get('serial_no')

            if isbn:
                item.isbn = isbn
            if serial_no:
                item.serial_no = serial_no

            item.save(generate_barcode=generate_barcode,
                      generate_qrcode=generate_qrcode)

            # Save photos for the item
            files = request.FILES.getlist('photos')
            for file in files:
                Photo.objects.create(item=item, photo=file)

            # Create a stock entry for the item
            quantity = request.POST.get('quantity')
            last_quantity_added = request.POST.get('last_quantity_added')
            last_quantity_reduced = request.POST.get('last_quantity_reduced')

            Stock.objects.create(
                item=item,
                warehouse=item.warehouse,
                quantity=quantity,
                last_quantity_added=last_quantity_added,
                last_quantity_reduced=last_quantity_reduced
            )

            context['alert_message'] = 'Successfully Added an Item'
            # update context after save
            context['items'] = Item.objects.all()
            data['valid'] = True
            data['item_list'] = render_to_string(
                'contents/item/item-list.html', context, request=request)
            data['alert_box'] = render_to_string(
                'includes/alert-box.html', context, request=request)
        else:
            print("Form is invalid")
            print(form.errors)

    data['add_item_form'] = render_to_string(
        'contents/item/add-item-form.html', context, request=request)

    return JsonResponse(data)


# def add_item(request):
#     context = {}
#     data = {}

#     warehouses = Warehouse.objects.all()
#     categories = ItemCategory.objects.all()
#     units = ItemUnit.objects.all()
#     random_unique_id = generate_unique_id()
#     # UNIT_CHOICES = Item.UNIT_CHOICES

#     context['warehouses'] = warehouses
#     context['categories'] = categories
#     context['units'] = units
#     context['random_unique_id'] = random_unique_id
#     # context['unit_choices'] = UNIT_CHOICES
#     context['table_name'] = "item"
#     context['items'] = Item.objects.all()

#     if request.method == "POST":
#         form = ItemForm(request.POST, request.FILES)

#         if form.is_valid():
#             item = form.save()

#             # Save photos for the item
#             files = request.FILES.getlist('photos')
#             for file in files:
#                 Photo.objects.create(item=item, photo=file)

#             # Create a Item Category entry for the item
#             category = request.POST.get('category')

#             ItemCategory.objects.create(
#                 item=item,
#                 name=category,
#             )

#             # Create a Item Unit entry for the item
#             unit = request.POST.get('unit')

#             ItemUnit.objects.create(
#                 item=item,
#                 name=unit,
#             )

#             # Create a stock entry for the item
#             quantity = request.POST.get('quantity')
#             last_quantity_added = request.POST.get('last_quantity_added')
#             last_quantity_reduced = request.POST.get('last_quantity_reduced')

#             Stock.objects.create(
#                 item=item,
#                 warehouse=item.warehouse,
#                 quantity=quantity,
#                 last_quantity_added=last_quantity_added,
#                 last_quantity_reduced=last_quantity_reduced
#             )

#             context['alert_message'] = 'Successfully Added an Item'
#             # update context after save
#             context['items'] = Item.objects.all()
#             data['valid'] = True
#             data['item_list'] = render_to_string(
#                 'contents/item/item-list.html', context, request=request)
#             data['alert_box'] = render_to_string(
#                 'includes/alert-box.html', context, request=request)

#     data['add_item_form'] = render_to_string(
#         'contents/item/add-item-form.html', context, request=request)

#     return JsonResponse(data)


# def add_item(request):
#     context = {}
#     data = {}

#     warehouses = Warehouse.objects.all()
#     categories = ItemCategory.objects.all()
#     units = ItemUnit.objects.all()
#     random_unique_id = generate_unique_id()

#     context['warehouses'] = warehouses
#     context['categories'] = categories
#     context['units'] = units
#     context['random_unique_id'] = random_unique_id
#     context['table_name'] = "item"
#     context['items'] = Item.objects.all()

#     if request.method == "POST":
#         form = ItemForm(request.POST, request.FILES)

#         if form.is_valid():
#             item = form.save(commit=False)

#             item.save()

#             # Save photos for the item
#             files = request.FILES.getlist('photos')
#             for file in files:
#                 Photo.objects.create(item=item, photo=file)

#             # Create a stock entry for the item
#             quantity = request.POST.get('quantity')
#             last_quantity_added = request.POST.get('last_quantity_added')
#             last_quantity_reduced = request.POST.get('last_quantity_reduced')

#             Stock.objects.create(
#                 item=item,
#                 warehouse=item.warehouse,
#                 quantity=quantity,
#                 last_quantity_added=last_quantity_added,
#                 last_quantity_reduced=last_quantity_reduced
#             )

#             context['alert_message'] = 'Successfully Added an Item'
#             # update context after save
#             context['items'] = Item.objects.all()
#             data['valid'] = True
#             data['item_list'] = render_to_string(
#                 'contents/item/item-list.html', context, request=request)
#             data['alert_box'] = render_to_string(
#                 'includes/alert-box.html', context, request=request)
#         else:
#             print("Form is invalid")
#             print(form.errors)

#     data['add_item_form'] = render_to_string(
#         'contents/item/add-item-form.html', context, request=request)

#     return JsonResponse(data)


# def update_item(request, id):

#     context = {}
#     data = {}

#     single_item = get_object_or_404(Item, id=id)
#     warehouses = Warehouse.objects.all()
#     categories = ItemCategory.objects.all()
#     units = ItemUnit.objects.all()

#     context['single_item'] = single_item
#     context['warehouses'] = warehouses
#     context['categories'] = categories
#     context['units'] = units

#     context['items'] = Item.objects.all()

#     data['valid'] = False
#     data['update_item_form'] = render_to_string(
#         'contents/item/update-item-form.html', context, request=request)

#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES,
#                         instance=single_item)

#         if form.is_valid():
#             form.save()

#             context['items'] = Item.objects.all()
#             context['alert_message'] = 'Successfully Updated a item'

#             data['valid'] = True
#             data['item_list'] = render_to_string(
#                 'contents/item/item-list.html', context, request=request)
#             data['alert_box'] = render_to_string(
#                 'includes/alert-box.html', context, request=request)

#     return JsonResponse(data)

def update_item(request, id):
    context = {}
    data = {}

    single_item = get_object_or_404(Item, id=id)
    warehouses = Warehouse.objects.all()
    categories = ItemCategory.objects.all()
    units = ItemUnit.objects.all()
    # Add this line to get related photos
    photos = Photo.objects.filter(item=single_item)

    context['single_item'] = single_item
    context['warehouses'] = warehouses
    context['categories'] = categories
    context['units'] = units
    context['items'] = Item.objects.all()
    context['photos'] = photos  # Include photos in the context

templates/contents/item/add-item-form.html
{% load static %}

<form action="{% url 'inventory_app:add_item' %}" method="post" class="add_item_form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="modal-header">
    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Item Form</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="row">

      <!-- Left Column: Item details -->
      <div class="col-md-4">
        <div class="mb-3">
          <label class="form-label" for="name">Name</label>
          <input class="form-control" name="name" id="name" type="text" placeholder="Item Name" required />
        </div>
        <div class="mb-3">
          <label class="form-label" for="description">Description</label>
          <textarea class="form-control" name="description" id="description" rows="3" placeholder="Item Description"
            required></textarea>
        </div>
        <div class="mb-3">
          <label class="form-label" for="warehouse">Warehouse</label>
          <select class="form-control" name="warehouse" id="warehouse" required>
            <option value="" disabled selected>Select Warehouse</option>
            {% for warehouse in warehouses %}
            <option value="{{ warehouse.id }}">{{ warehouse.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label class="form-label" for="category">Category</label>
          <select class="form-control" name="category" id="category" required>
            <option value="" disabled selected>Select Category</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>


        <!-- Code type selection -->
        <div class="mb-3">
          <label class="form-label">Which type of code you want for your item?</label><br>
          <input type="checkbox" id="barcode" name="barcode" value="1">
          <label for="barcode">BarCode</label><br>
          <input type="checkbox" id="qrcode" name="qrcode" value="1">
          <label for="qrcode">QRCode</label><br>
          <input type="checkbox" id="isbn_checkbox" name="isbn_checkbox" value="1"
            onchange="toggleInputField('isbn', this)">
          <label for="isbn_checkbox">ISBN</label><br>
          <input type="checkbox" id="serial_no_checkbox" name="serial_no_checkbox" value="1"
            onchange="toggleInputField('serial_no', this)">
          <label for="serial_no_checkbox">Serial No</label><br>
        </div>

        <!-- ISBN and Serial No input fields -->
        <div class="mb-3" id="isbn_input" style="display:none;">
          <label class="form-label" for="isbn">ISBN</label>
          <input class="form-control" name="isbn" id="isbn" type="text" placeholder="ISBN" />
        </div>
        <div class="mb-3" id="serial_no_input" style="display:none;">
          <label class="form-label" for="serial_no">Serial No</label>
          <input class="form-control" name="serial_no" id="serial_no" type="text" placeholder="Serial No" />
        </div>


        <div class="mb-3">
          <label class="form-label" for="unit">Unit</label>
          <select class="form-control" name="unit" id="unit" required>
            <option value="" disabled selected>Select Unit</option>
            {% for unit in units %}
            <option value="{{ unit.id }}">{{ unit.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label class="form-label" for="price_per_unit">Price Per Unit</label>
          <input class="form-control" name="price_per_unit" id="price_per_unit" type="number" step="0.01"
            placeholder="Price Per Unit" required />
        </div>

        <div class="mb-3" style="display: none;">
          <label class="form-label" for="random_unique_id">Unique ID</label>
          <input class="form-control" name="random_unique_id" id="random_unique_id" type="text" placeholder="Unique ID"
            value="{{ random_unique_id }}" readonly />
        </div>
      </div>

      <!-- Middle Column: Photo Upload Section -->

      <div id="photo-upload" class="col-md-4" style="border: 2px dashed #ccc;">

        <div class="mb-3">
          <label class="form-label" for="photos">Upload Photos</label>


          <!-- Input field should keep outside drop area to click on full drop area  -->

          <input class="form-control" name="photos" id="photos" type="file" accept="image/*" multiple
            style="display: none;" />

          <div id="drop-area"
            style="border: 1px dashed #ccc; padding: 25px; text-align: center; cursor: pointer; margin-top: 10px;">

            <img src="{% static 'inventory_app/assets/img/icons/cloud-upload.svg' %}" width="15%" alt="">
            <p id="upload-text-new" style="margin: 0;">Drag and drop photos here or click to upload</p>
            <p id="upload-text" style="color: blue; text-decoration: underline; cursor: pointer;">
              Upload from device
            </p>

          </div>


          <div style="margin-top: 10px;" id="existing-photo-preview-container"></div>
          <div id="photo-preview-container" style="width: 100%;">
            <div id="photo-previews"></div>
          </div>

        </div>

      </div>

      <!-- Right Column: Stock details -->
      <div class="col-md-4">
        <div class="mb-3">
          <label class="form-label" for="quantity">Quantity</label>
          <input class="form-control" name="quantity" id="quantity" type="number" step="1" placeholder="Quantity"
            required />
        </div>
        <div class="mb-3">
          <label class="form-label" for="last_quantity_added">Last Quantity Added</label>
          <input class="form-control" name="last_quantity_added" id="last_quantity_added" type="number" step="1"
            placeholder="Last Quantity Added" required />
        </div>
        <div class="mb-3">
          <label class="form-label" for="last_quantity_reduced">Last Quantity Reduced</label>
          <input class="form-control" name="last_quantity_reduced" id="last_quantity_reduced" type="number" step="1"
            placeholder="Last Quantity Reduced" required />
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>


<script>
  function toggleInputField(fieldId, checkbox) {
    var inputField = document.getElementById(fieldId + '_input');
    if (checkbox.checked) {
      inputField.style.display = 'block';
    } else {
      inputField.style.display = 'none';
    }
  }
</script>

<script>
  $(document).ready(function () {
    let uploadedFiles = [];

    $('#photos').on('change', handleFileSelect);


    $('#drop-area').on('click', function () {
      console.log("Drop Area Clicked")
      $('#photos').click();
    });


    function handleFileSelect(event) {
      const files = event.target.files;
      uploadedFiles = uploadedFiles.concat(Array.from(files));
      updatePreview();
    }

    function updatePreview() {
      const previewContainer = $('#photo-preview-container');
      const previewDiv = $('#photo-previews');
      previewDiv.empty(); // Clear previous previews

      uploadedFiles.forEach((file, index) => {
        const reader = new FileReader();
        reader.onload = function (e) {
          const imgWrapper = $('<div></div>').css({
            position: 'relative',
            display: 'inline-block',
            margin: '5px'
          });

          const img = $('<img>').attr('src', e.target.result).css({
            maxWidth: '100px',
            height: 'auto'
          });

          const removeButton = $('<span>&times;</span>').css({
            position: 'absolute',
            top: '0',
            right: '0',
            color: 'white',
            fontSize: '30px',
            lineHeight: '20px',
            cursor: 'pointer',
            padding: '4px'
          }).on('click', function () {
            removeFile(index);
          });

          imgWrapper.append(img).append(removeButton);
          previewDiv.append(imgWrapper);
        };
        reader.readAsDataURL(file);
      });
      previewContainer.show();
    }

    function removeFile(index) {
      uploadedFiles.splice(index, 1);
      updateFileList();
      updatePreview();
    }

    function updateFileList() {
      const dataTransfer = new DataTransfer();
      uploadedFiles.forEach(file => {
        dataTransfer.items.add(file);
      });
      $('#photos')[0].files = dataTransfer.files;
    }

    const dropArea = $('#drop-area');

    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
      dropArea.on(eventName, preventDefaults);
    });

    function preventDefaults(e) {
      e.preventDefault();
      e.stopPropagation();
    }

    dropArea.on('drop', handleDrop);

    function handleDrop(e) {
      const dt = e.originalEvent.dataTransfer;
      const files = dt.files;
      uploadedFiles = uploadedFiles.concat(Array.from(files));
      updateFileList();
      updatePreview();
    }

    // AJAX for fetching units based on selected category
    $('#category').on('change', function () {
      const categoryId = $(this).val();
      const unitSelect = $('#unit');
      unitSelect.html('<option value="" disabled selected>Loading...</option>');

      $.ajax({
        url: `/get-units/?category_id=${categoryId}`,
        method: 'GET',
        dataType: 'json',
        success: function (data) {
          unitSelect.html('<option value="" disabled selected>Select Unit</option>');
          data.forEach(unit => {
            unitSelect.append(`<option value="${unit.id}">${unit.name}</option>`);
          });
        }
      });
    });
  });
</script>

templates/contents/item/delete-item-form.html
<form action="{% url 'inventory_app:delete_item' single_item.id %}" method="post" class="delete_item_form">
  {% csrf_token %}

  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Confirmation of Delete item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <h6>Are you sure you want to delete the "{{ single_item.name }}"?</h6>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

templates/contents/item/item-list.html
{% for item in items %}
  <tr>
    <td class="align-middle ps-3 name">
      <input type="checkbox" name="" id="" />
    </td>
    <td class="text-center">{{ forloop.counter }}</td>
    <td class="text-center">{{ item.name }}</td>
    <td class="text-center">{{ item.description }}</td>
    <td class="align-middle">{{ item.warehouse }}</td>
    <td class="align-middle">{{ item.category }}</td>
    <td class="align-middle">{{ item.unit }}</td>
    <td class="align-middle">{{ item.price_per_unit }}</td>
    <td class="align-middle">{{ item.random_unique_id }}</td>
    <td class="align-middle white-space-nowrap text-end pe-0">
      <div class="btn-reveal-trigger position-static">
        <button class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs-10" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent"><span class="fas fa-ellipsis-h fs-10"></span></button>

        <div class="dropdown-menu dropdown-menu-end py-2">
          <a class="dropdown-item" href="#!">View</a>
          <a class="dropdown-item update_item_button" href="{% url 'inventory_app:update_item' item.id %}">Edit</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger delete_item_button" href="{% url 'inventory_app:delete_item' item.id %}">Remove</a>
        </div>
      </div>
    </td>
  </tr>
{% endfor %}